<div align="center" style="font-size: xx-large; color:#279D9F">Máster en Big Data y Data Science</div><br>
<div align="center" style="font-size: x-large; color:#6E6E6E">Librerías básicas de Python: NumPy</div><br>
<div align="center" style="font-size: large; color:#279D9F">Carlos María Alaíz Gudín - Universidad Autónoma de Madrid</div><br>

# Introducción

Este Notebook incluye el contenido correspondiente al bloque de NumPy, tanto los ejemplos mostrados en los distintos vídeos como los ejercicios propuestos.

## Preliminares

In [1]:
# La librearía numpy se suele importar como np.
import numpy as np

# La clase `ndarray`

## El objeto `ndarray`

### `ndarray`

In [3]:
# Array 1-dimensional (vector).
vector = np.array([1, 2, 3, 4])
print(vector)

[1 2 3 4]


In [4]:
# Array 2-dimensional (matriz).
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Array 3-dimensional (tensor).
tensor = np.array([[[1, 2], [3, 4], [5, 6]],[[7, 8], [9, 10], [11, 12]]])
print(tensor)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### `shape`

In [6]:
# Vector de 4 elementos.
print(vector.shape)

(4,)


In [7]:
# Matriz 2x4.
print(matriz.shape)

(2, 4)


In [8]:
#Tensor 2x3x2.
print(tensor.shape)

(2, 3, 2)


### `dtype`

In [9]:
# Matriz de enteros.
print(matriz.dtype)

int32


## Creación de arrays

### Creación

In [10]:
# Creación de un ndarray a partir de una lista.
vector = np.array([1, 2, 3, 4])
print(vector)

[1 2 3 4]


In [11]:
# Creación de un ndarray a partir de una lista anidada.
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# Creación de un ndarray a partir de otro.
vector_new = np.array(vector)
print(vector_new)

[1 2 3 4]


### `dtype`

In [13]:
# El tipo se ajusta al mínimo válido para todos los elementos del array.
vector_i = np.array([1, 2, 3])
print(vector_i, "\t=>\t", vector_i.dtype)

vector_f = np.array([1, 2, 3.0])
print(vector_f, "\t=>\t", vector_f.dtype)

[1 2 3] 	=>	 int32
[1. 2. 3.] 	=>	 float64


In [14]:
# También se puede espeficiar el tipo del array.
vector_i = np.array([1, 2, 3], dtype=float)
print(vector_i, "\t=>\t", vector_i.dtype)

[1. 2. 3.] 	=>	 float64


### `ndmin`

In [15]:
# Se puede especificar el mínimo número de dimensiones.
matriz = np.array([1, 2, 3, 4], ndmin = 2)
print(matriz)

[[1 2 3 4]]


## Ejercicios: Creación de arrays

### Enunciado

1. Crea una matriz de ceros de dimensiones $2 \times 3$.
1. Crea una matriz de unos con el mismo y dimensiones que la matriz anterior.
1. Crea un tensor vacío de dimensiones $3 \times 2 \times 4$.
1. Crea un vector con números del $1$ al $30$.
1. Crea un array que contenga los nombres de los días de la semana. ¿Qué tipo tiene?

### Respuesta

In [12]:
matriza = np.zeros([2,2])
matrizb = np.ones_like(matriza)
matrizc = np.empty([3,2,4])
matrizd = np.arange(1,31)
matrizf = np.array(['Lunes','Martes','Miercoles','Jueves'])


TypeError: object of type 'int' has no len()

## Operaciones básicas con arrays

### Operaciones con escalares

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
# Suma de matriz y escalar.
print(matriz)
print("+   2")
print("-------")
print(matriz + 2)

[[1 2 3 4]]
+   2
-------
[[3 4 5 6]]


In [38]:
# Producto de matriz y escalar.
print(matriz)
print("x   4")
print("---------")
print(matriz * 4)

[[1 2 3 4]]
x   4
---------
[[ 4  8 12 16]]


### Operaciones entre arrays de la misma dimensión

In [39]:
vector_1 = np.array([3, 4, 5])
vector_2 = np.array([1, 2, 3])
matriz_1 = np.array([[2, 4], [6, 8]])
matriz_2 = np.array([[1, 2], [3, 4]])

In [40]:
# Resta de vectores.
print(vector_1)
print("-")
print(vector_2)
print("-------")
print(vector_1 - vector_2)

[3 4 5]
-
[1 2 3]
-------
[2 2 2]


In [41]:
# División de matrices.
print(matriz_1)
print("/")
print(matriz_2)
print("-------")
print(matriz_1 / matriz_2)

[[2 4]
 [6 8]]
/
[[1 2]
 [3 4]]
-------
[[2. 2.]
 [2. 2.]]


## Ejercicios: Operaciones básicas con arrays

### Enunciado

1. Crea una matriz cuadrada $5 \times 5$ tal que:
    - Los elementos de la diagonal son todos $10$.
    - Los elementos fuera de la diagonal son todos $5$.

### Respuesta

In [52]:
matrize = np.identity(5)*10

for i in [-4,-3,-2,-1,1,2,3,4]:
    matrize = matrize + np.eye(5,k=i)*5
    
print(matrize)

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]]


# Indexación y *slicing*

## Indexación de arrays unidimensionales y multidimensionales

### Arrays unidimensionales

In [53]:
# Array unidimensional con números del 0 al 9.
vector = np.arange(10)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
# Acceso al elemento en la posición 4.
print(vector)
print(vector[4])

[0 1 2 3 4 5 6 7 8 9]
4


In [55]:
# Acceso a los elementos entre las posiciones 2 (incluida) y 7 (excluida).
print(vector)
print(vector[2:7])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]


In [56]:
# Acceso a los 3 últimos elementos.
print(vector)
print(vector[-3:])

[0 1 2 3 4 5 6 7 8 9]
[7 8 9]


### Modificación de arrays

In [57]:
# Array unidimensional con números del 0 al 9.
vector = np.arange(10)

In [58]:
# Modificación del elemento de la posición 2.
print(vector)
vector[2] = 0
print(vector)

[0 1 2 3 4 5 6 7 8 9]
[0 1 0 3 4 5 6 7 8 9]


In [59]:
# Modificación de los elementos de la slice vector[1:5].
print(vector)
vector[1:5] = 0
print(vector)

[0 1 0 3 4 5 6 7 8 9]
[0 0 0 0 0 5 6 7 8 9]


In [60]:
# Modificación a través de una referencia.
print(vector)
subvector = vector[1:5]
subvector[2] = 9999
print(vector)

[0 0 0 0 0 5 6 7 8 9]
[   0    0    0 9999    0    5    6    7    8    9]


In [61]:
# Modificación de una copia.
vector = np.arange(10)
print(vector)
subvector = vector[1:5].copy()
subvector[2] = 9999
print(vector)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### Arrays multidimensionales

In [62]:
# Matriz con elementos del 1 al 16.
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [63]:
# Acceso al elemento de la posición (1, 2).
print(matriz)
print(matriz[1, 2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7


In [64]:
# Acceso a los elementos de las filas 1 y 2 y tres últimas columnas.
print(matriz)
print(matriz[1:3, -3:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7  8]
 [10 11 12]]


## Ejercicios: Indexación de arrays unidimensionales y multidimensionales 1

### Enunciado

Dada la matriz generada más abajo:
1. Cambia el elemento de la posición $(3, 2)$ para que tenga un $3$.
1. Realiza una copia independiente de las dos primeras filas en otra variable.
1. Accede a los elementos de las dos últimas filas y dos últimas columnas.

In [66]:
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


### Respuesta

In [74]:
matriz[2,1]=3
matrizb = matriz[:2,:].copy()
matriz[-2:,-2:]


array([[ 3, 16],
       [19, 20]])

## Ejercicios: Indexación de arrays unidimensionales y multidimensionales 2

### Enunciado

Dado el código de más abajo:
1. ¿Cuál es el contenido de `y`? ¿Por qué?
1. ¿Cuál es el contenido de `x`? ¿Por qué?

In [3]:
x = np.array([1, 2, 3, 4, 5])
y = x[:3]
y[:] = 100 * y[:]

### Respuesta

In [5]:
y

array([100, 200, 300])

## Indexación booleana

In [6]:
# Matriz de números aleatorios.
matriz = np.random.randn(10, 3)

### Selección de filas

In [7]:
# Índice booleano, marca la posición de las filas cuyo primer elemento es positivo.
print(matriz)
ix = matriz[:, 0] > 0
print(ix)

[[-1.18840326  2.04429777  0.82204503]
 [-0.17814287 -2.91553686 -0.7191218 ]
 [ 1.48721609  1.31768094 -0.09296558]
 [-0.80226358  0.86421648 -0.64503063]
 [ 0.07573402  0.16064333  1.0223467 ]
 [-0.88225433  1.99921255  1.46042681]
 [ 1.99655644 -0.08497719 -1.80999362]
 [-0.74911213  0.35895399  0.24510652]
 [-0.56929731 -0.16656755  0.83270853]
 [-0.22070151  0.03805925  1.10840539]]
[False False  True False  True False  True False False False]


In [8]:
# Selección con el índice booleano.
submatriz = matriz[ix, :]
print(submatriz)

[[ 1.48721609  1.31768094 -0.09296558]
 [ 0.07573402  0.16064333  1.0223467 ]
 [ 1.99655644 -0.08497719 -1.80999362]]


In [9]:
# Selección de las filas cuyo primer y último elemento es positivo.
submatriz = matriz[(matriz[:, 0] > 0) & (matriz[:, -1] > 0)]
print(submatriz)

[[0.07573402 0.16064333 1.0223467 ]]


In [10]:
# Selección de las filas cuyo primer elemento no es positivo o cuyo último elemento sí lo es.
submatriz = matriz[~(matriz[:, 0] > 0) | (matriz[:, -1] > 0)]
print(submatriz)

[[-1.18840326  2.04429777  0.82204503]
 [-0.17814287 -2.91553686 -0.7191218 ]
 [-0.80226358  0.86421648 -0.64503063]
 [ 0.07573402  0.16064333  1.0223467 ]
 [-0.88225433  1.99921255  1.46042681]
 [-0.74911213  0.35895399  0.24510652]
 [-0.56929731 -0.16656755  0.83270853]
 [-0.22070151  0.03805925  1.10840539]]


### Selección de componentes

In [13]:
# Modificación de las entradas negativas.
matriz[matriz < 0] = 0
print(matriz)

[[0.         2.04429777 0.82204503]
 [0.         0.         0.        ]
 [1.48721609 1.31768094 0.        ]
 [0.         0.86421648 0.        ]
 [0.07573402 0.16064333 1.0223467 ]
 [0.         1.99921255 1.46042681]
 [1.99655644 0.         0.        ]
 [0.         0.35895399 0.24510652]
 [0.         0.         0.83270853]
 [0.         0.03805925 1.10840539]]


### Cambios en la selección

In [ ]:
# Modificación a través de una referencia.
submatriz = matriz[matriz[:,0] > 0, :]
print(submatriz)
submatriz[:] = 2
print(matriz)

## Ejercicios: Indexación booleana

### Enunciado

Dado el array generado a continuación, que contiene una lista con $100$ notas aleatorias entre $0$ y $10$, construye un array que contenga, para cada nota numérica, su nota cualitativa de acuerdo al siguiente esquema:
* $[0, 5)$: `"SUSPENSO"`.
* $[5, 7)$: `"APROBADO"`.
* $[7, 9)$: `"NOTABLE"`.
* $[9, 10]$: `"SOBRESALIENTE"`.

**Nota**: Hay que poner como tipo `'S13'`, la longitud de la cadena más larga que se quiere almacenar, al crear el array de notas.

In [2]:
n = 100
np.random.seed(13)
notas_n = np.random.rand(n) * 10
notas_c = np.empty_like(notas_n, dtype='<U13')    

### Respuesta

In [9]:
notas_c[notas_n < 5] = 'SUSPENSO'
notas_c[(notas_n > 5) & (notas_n < 7)] = 'APROBADO'
notas_c[(notas_n > 7) & (notas_n < 9)] = 'NOTABLE'
notas_c[notas_n > 9] = 'SOBRESALIENTE'


## Indexación *fancy*

In [10]:
# Creación de la matriz.
nfil = 5
ncol = 3
p = 1

matriz = np.empty((nfil, ncol))
for i in range(ncol):
    matriz[:, i] = np.arange(nfil) * p
    p *= 10

### Selección por filas

In [13]:
# Selección de las filas 3 y 2, en este orden.
print(matriz)
print(matriz[[3, 2]])

[[  0.   0.   0.]
 [  1.  10. 100.]
 [  2.  20. 200.]
 [  3.  30. 300.]
 [  4.  40. 400.]]
[[  3.  30. 300.]
 [  2.  20. 200.]]


### Selección por columnas

In [14]:
# Selección de las columnas 2 y 0, en este orden.
print(matriz)
print(matriz[:, [2, 0]])


[[  0.   0.   0.]
 [  1.  10. 100.]
 [  2.  20. 200.]
 [  3.  30. 300.]
 [  4.  40. 400.]]
[[  0.   0.]
 [100.   1.]
 [200.   2.]
 [300.   3.]
 [400.   4.]]


### Selección entrada a entrada

In [15]:
# Selección de las entradas (3, 2) y (2, 0).
print(matriz)
print(matriz[[3, 2], [2, 0]])

[[  0.   0.   0.]
 [  1.  10. 100.]
 [  2.  20. 200.]
 [  3.  30. 300.]
 [  4.  40. 400.]]
[300.   2.]


### Cambios en la selección

In [16]:
# Modificación a través de una referencia usando indexación fancy o por slices.
matriz_1 = matriz.copy()
matriz_2 = matriz.copy()

submatriz_1 = matriz_1[[0,1]]
submatriz_2 = matriz_2[:2]

print('Submatriz fancy:\n', submatriz_1)
print('Submatriz slice:\n', submatriz_2)

submatriz_1[:] = 999
submatriz_2[:] = 999

print('Submatriz fancy:\n', submatriz_1)
print('Submatriz slice:\n', submatriz_2)

print('Matriz fancy:\n', matriz_1)
print('Matriz slice:\n', matriz_2)

Submatriz fancy:
 [[  0.   0.   0.]
 [  1.  10. 100.]]
Submatriz slice:
 [[  0.   0.   0.]
 [  1.  10. 100.]]
Submatriz fancy:
 [[999. 999. 999.]
 [999. 999. 999.]]
Submatriz slice:
 [[999. 999. 999.]
 [999. 999. 999.]]
Matriz fancy:
 [[  0.   0.   0.]
 [  1.  10. 100.]
 [  2.  20. 200.]
 [  3.  30. 300.]
 [  4.  40. 400.]]
Matriz slice:
 [[999. 999. 999.]
 [999. 999. 999.]
 [  2.  20. 200.]
 [  3.  30. 300.]
 [  4.  40. 400.]]


## Ejercicios: Indexación *fancy*

### Enunciado

Dado el array generado a continuación:
1. Selecciona solo las entradas $2$, $1$ y $4$, en ese orden.
1. Invierte el array, recorriéndolo en orden contrario.

In [17]:
vector = np.array(['a', 'b', 'c', 'd', 'e'])

### Respuesta

In [35]:
subvectora = vector[[2,1,4]]
subvectorb = vector[[np.arange(4,-1,-1)]]
print(subvectora)
print(subvectorb)

['c' 'b' 'e']
['e' 'd' 'c' 'b' 'a']


C:\Users\Lucian\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


# Otras operaciones con arrays

## Transposición

### Matrices

In [36]:
# Creación de la matriz.
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [37]:
# Transposición con el atributo .T.
print(matriz)
print(matriz.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [38]:
# Transposición con la función transpose.
print(matriz)
print(matriz.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Vectores

In [39]:
# Transposición de un vector.
vector = np.arange(10)
print(vector)
print(vector.T)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### Tensores

In [40]:
# Transposición de un tensor.
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(tensor)
print(tensor.T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


## Ejercicios: Transposición

### Enunciado


Crea un vector columna con números del $0$ al $9$ usando las funciones `arange`, `array` (con el argumento `ndmin`) y `transpose`.

### Respuesta

In [46]:
vector = np.array(np.arange(10),ndmin=10).transpose()


array([[[[[[[[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]]]]]]]])

## Cambio de forma de un array y concatenación

In [3]:
# Array unidimensional con los elementos 1-12.
vector = np.arange(1, 13)

### `reshape`

In [4]:
# De vector 12 a matriz 3x4.
print(vector)
matriz_1 = vector.reshape(3, 4)
print(matriz_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# De vector 12 a matriz 2x6.
print(vector)
matriz_2 = vector.reshape(2, 6)
print(matriz_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
# De vector 12 a tensor 2x3x2.
print(vector)
tensor = vector.reshape(2, 3, 2)
print(tensor)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
# Comprobación de la coherencia de las dimensiones.
print(vector.shape, matriz_1.shape, matriz_2.shape, tensor.shape)

(12,) (3, 4) (2, 6) (2, 3, 2)


### `ravel`

In [8]:
# Desenrollado de las matrices y el tensor.
print(matriz_1.ravel())
print(matriz_2.ravel())
print(tensor.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### `newaxis`

In [9]:
# Creación de un tensor añadiendo un eje en medio.
tensor = matriz_1[:, np.newaxis, :]
print(tensor)
print(tensor.shape)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
(3, 1, 4)


In [10]:
# Recuperación de la matriz original.
matriz_3 = tensor[:, 0, :]
print(matriz_3)
print(matriz_3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


### `concatenate`

In [11]:
# Creación de matrices de ceros, unos y doses.
matriz_0 = np.zeros((2, 3))
matriz_1 = np.ones((3, 3))
matriz_2 = np.ones((2, 3)) * 2

In [12]:
# Concatenación a lo largo del eje 0.
print(np.concatenate((matriz_0, matriz_1, matriz_2), axis = 0))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [13]:
# Creación de matrices de ceros y unos.
matriz_0 = np.zeros((3, 4))
matriz_1 = np.ones((3, 2))

In [14]:
# Concatenación a lo largo del eje 1.
print(np.concatenate((matriz_0, matriz_1), axis = 1))

[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]]


## Ejercicios: Cambio de forma de un array y concatenación

### Enunciado

A continuación se genera un array de $20$ notas aleatorias, entre $0$ y $10$.
Suponiendo que el array representa la nota de $5$ alumnos, listados en el array `alumnos`, en las $4$ asignaturas del array `asignaturas`, y que en el array están primero las notas del primer alumno, luego las del segundo, etc., y que para cada alumno aparecen en el orden indicado en el array `asignaturas`, transforma el array para que se muestren las notas en forma de matriz, donde cada fila corresponda a un alumno, y cada columna a una asignatura.

In [15]:
alumnos = np.array(['Juan', 'Mónica', 'Ana', 'Raúl', 'Carmen'])
asignaturas = np.array(['Matemáticas', 'Inglés', 'Literatura', 'Historia'])

np.random.seed(13)
notas = np.random.rand(len(alumnos) * len(asignaturas)) * 10
print(notas)

[7.77702411 2.3754122  8.24278533 9.65749198 9.72601114 4.53449247
 6.09042463 7.75526515 6.41613345 7.2201823  0.35036524 2.98449471
 0.58512492 8.57060943 3.72854028 6.79847952 2.56279949 3.47581215
 0.0941277  3.58333783]


### Respuesta

In [16]:
notas_bien = notas.reshape(5,4)
print(notas_bien)

[[7.77702411 2.3754122  8.24278533 9.65749198]
 [9.72601114 4.53449247 6.09042463 7.75526515]
 [6.41613345 7.2201823  0.35036524 2.98449471]
 [0.58512492 8.57060943 3.72854028 6.79847952]
 [2.56279949 3.47581215 0.0941277  3.58333783]]


### Enunciado

En la siguiente celda se define el array `x`, que tiene el siguiente aspecto:
$$ x = \begin{pmatrix} 1 & 1 & 1 \\ 1 & 0 & 0 \\ 1 & 0 & 0 \end{pmatrix} . $$
A partir de `x`, definir un array con el siguiente contenido:
$$ \begin{pmatrix} 1 & 1 & 1 & 1 & 1 & 1 \\ 1 & 0 & 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 & 0 & 1 \\ 1 & 1 & 1 & 1 & 1 & 1 \end{pmatrix} . $$
**Nota**: Debería bastar con dos líneas de código.

In [17]:
x = np.array([[1, 1, 1], [1, 0, 0], [1, 0, 0]])

print(x)

[[1 1 1]
 [1 0 0]
 [1 0 0]]


### Respuesta

In [47]:
a = np.concatenate((x,x[::-1]),axis=0)
b = np.concatenate((x[0][::-1],x[1][::-1],x[2][::-1],x[1][::-1],x[1][::-1],x[0][::-1])).reshape(6,3)
c = np.concatenate((a,b),axis=1)
c

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

## Funciones universales

In [48]:
# Creación de la matriz.
matriz = np.array([[1, 4, 9], [16, 25, 36], [49, 64, 81]])

### sqrt

In [49]:
# Cálculo de la raíz cuadrada (elemento a elemento).
print(matriz)
print(np.sqrt(matriz))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Tiempo de ejecución

In [56]:
# Creación del array, 10000 puntos entre 0 y 2 pi.
x = np.linspace(0, 2 * np.pi, 10000)

In [57]:
# Tiempo de cálculo del seno directamente.
%time y = np.sin(x)

Wall time: 0 ns


In [58]:
# Tiempo de cálculo del seno con un bucle.
%time y = np.array([np.sin(elem) for elem in x])

Wall time: 28.9 ms


## Ejercicios: Funciones universales

### Enunciado

A continuación se generan $2$ vectores conteniendo $5$ notas aleatorias, entre $0$ y $10$, correspondientes a las notas de $5$ alumnos en dos exámenes.
Suponiendo que se retenga la nota más alta entre ambos exámenes:
1. Calcula un vector que contenga, para cada alumno, su nota máxima, usando la función de NumPy `maximum`.
1. Convierte el vector anterior de notas al rango $[1, 4]$.

In [59]:
n = 5
np.random.seed(123)

notas_1 = 10 * np.random.rand(n)
notas_2 = 10 * np.random.rand(n)

print(notas_1)
print(notas_2)

[6.96469186 2.86139335 2.26851454 5.51314769 7.1946897 ]
[4.2310646  9.80764198 6.84829739 4.80931901 3.92117518]


### Respuesta

In [61]:
np.maximum(notas_1,notas_2)

array([6.96469186, 9.80764198, 6.84829739, 5.51314769, 7.1946897 ])

# Álgebra lineal

## Módulo `linalg`

### Producto escalar

In [62]:
# Creación de los dos vectores.
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([2, 3, 4])

In [63]:
# Producto escalar (con ambas sintáxis, aunque la segunda suele ser más cómoda).
print(vector_1, "x", vector_2, "=", np.dot(vector_1, vector_2))
print(vector_1, "x", vector_2, "=", vector_1 @ vector_2)

[1 2 3] x [2 3 4] = 20
[1 2 3] x [2 3 4] = 20


### Producto matricial

In [64]:
# Creación de dos matrices.
matriz_1 = np.array([[1, 1, 0], [2, 1, 0]])
matriz_2 = np.array([[1, 1], [1, 1], [0, 2]])

In [65]:
# Producto matricial.
print(matriz_1, "\n x \n", matriz_2, "\n---------\n", matriz_1 @ matriz_2)

[[1 1 0]
 [2 1 0]] 
 x 
 [[1 1]
 [1 1]
 [0 2]] 
---------
 [[2 2]
 [3 3]]


### Traza

In [66]:
# Creación de una matriz cuadrada simétrica.
matriz = np.random.randint(0, 5, size = (3, 3))
matriz = matriz + matriz.T

In [67]:
# Traza.
print(matriz)
print(matriz.trace())

[[0 5 7]
 [5 0 1]
 [7 1 6]]
6


### Determinante

In [73]:
# Determinante.
print(matriz)
print(np.linalg.det(matriz))

[[0 5 7]
 [5 0 1]
 [7 1 6]]
-79.99999999999997


### Inversa

In [71]:
# Inversa.
matriz_inv = np.linalg.inv(matriz)
print(matriz_inv)

[[ 0.0125  0.2875 -0.0625]
 [ 0.2875  0.6125 -0.4375]
 [-0.0625 -0.4375  0.3125]]


In [72]:
# El producto debería dar la identidad.
print(matriz_inv @ matriz)

[[ 1.00000000e+00  6.93889390e-17  5.55111512e-17]
 [ 1.11022302e-16  1.00000000e+00 -6.66133815e-16]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]


### Autovalores y autovectores

In [ ]:
# Cálculo de autovalores y autovectores.
v, w = np.linalg.eig(matriz)
print("Autovalores:\n", v)
print("\nAutovectores:\n", w)

## Ejercicios: Módulo `linalg`

### Enunciado

Dado el siguiente sistema lineal de ecuaciones:
$$ \left \{
\begin{matrix}
3x & + & y & + & 2z & = & 10\\
4x & + & 3y & + & 4z & = & 21\\
2x & + & y & + & 2z & = & 9\\
\end{matrix}
\right .
$$
1. Resuélvelo con NumPy usando la inversa.
1. Resuélvelo con NumPy usando la función `solve` del módulo `linalg`. Este método es, en general, más eficiente y estable numéricamente.

### Respuesta

In [81]:
matriz = [[3,1,2],[4,3,4],[2,1,2]]
coefs = [[10],[21],[9]]
soluciona = np.linalg.inv(matriz) @ coefs
solucionb = np.linalg.solve(matriz,coefs)
print(soluciona)
print(solucionb)

[[1.]
 [3.]
 [2.]]
[[1.]
 [3.]
 [2.]]


# Análisis de datos con NumPy

## Funciones estadísticas

In [82]:
# Creación de los datos.
datos = np.arange(1,11)
print(datos)

[ 1  2  3  4  5  6  7  8  9 10]


### Media, desviación, mínimo y máximo

In [83]:
print("Media = %.2f" % datos.mean())

Media = 5.50


In [84]:
print("Desviación = %.2f" % datos.std())

Desviación = 2.87


In [85]:
print("Minimo = %d" % datos.min())

Minimo = 1


In [86]:
print("Maximo = %d" % datos.max())

Maximo = 10


In [87]:
print("Posición mínimo = %d" % datos.argmin())

Posición mínimo = 0


In [88]:
print("Posición máximo = %d" % datos.argmax())

Posición máximo = 9


### Suma, producto

In [89]:
print("Suma = %d" % datos.sum())

Suma = 55


In [90]:
print("Producto = %d" % datos.prod())

Producto = 3628800


In [91]:
print("Suma acumulada =", datos.cumsum())

Suma acumulada = [ 1  3  6 10 15 21 28 36 45 55]


In [92]:
print("Producto acumulado =", datos.cumprod())

Producto acumulado = [      1       2       6      24     120     720    5040   40320  362880
 3628800]


### Estadísticas sobre matrices

In [93]:
# Creación de los datos.
datos = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(datos)

[[1 2 3 4]
 [5 6 7 8]]


In [94]:
# Cálculo de la media (sin argumentos, media de todos los elementos del array).
print("Media = %.2f" % datos.mean())

Media = 4.50


In [95]:
# Cálculo de la media de cada columna (eje 0).
print("Media =", datos.mean(axis = 0))

Media = [3. 4. 5. 6.]


In [96]:
# Cálculo de la media de cada columna (eje 1).
print("Media =", datos.mean(axis = 1))

Media = [2.5 6.5]


## Ejercicios: Funciones estadísticas

### Enunciado

Dado el array `notas` que contiene las notas de los alumnos listados en el array `alumnos`:
1. Calcular la nota media.
1. Imprimir el nombre de los alumnos cuya nota sea más de una desviación típica la nota media, y las respectivas notas.

In [119]:
np.random.seed(123)
alumnos = np.array(["JOSE", "ANTONIO", "JUAN", "MANUEL", "FRANCISCO", "LUIS", "JAVIER", "MIGUEL", "ANGEL", "CARLOS", "JESUS", "DAVID", "PEDRO", "DANIEL", "ALEJANDRO", "MARIA", "RAFAEL", "ALBERTO", "FERNANDO", "PABLO", "MARIA", "CARMEN", "ANA", "ISABEL", "DOLORES", "PILAR", "TERESA", "JOSEFA", "ROSA", "CRISTINA", "ANGELES", "ANTONIA", "LAURA", "ELENA", "FRANCISCA", "MARTA", "LUCIA", "MERCEDES", "LUISA", "CONCEPCION"])
notas = 10 * np.random.rand(len(alumnos))

(40,)


### Respuesta

In [133]:
print(notas.mean())
a = np.array(alumnos[notas > notas.mean() + notas.std()]).reshape(7,1)
b = np.array(notas[notas > notas.mean() + notas.std()]).reshape(7,1)

print(np.concatenate((a,b),axis=1))

4.975868023888985
[['JAVIER' '9.807641983846155']
 ['DAVID' '7.290497073840417']
 ['MARIA' '7.379954057320357']
 ['CARMEN' '8.494317940777895']
 ['ANA' '7.244553248606352']
 ['MERCEDES' '8.933891631171347']
 ['LUISA' '9.441600182038796']]


## La función `where`

In [134]:
# Creación de las lecturas y sus fechas.
fecha_1 = np.array(['2017-07-13', '2016-01-13', '2018-08-13', '2020-01-03'], dtype='datetime64')
lectura_1 = np.around(np.random.rand(len(fecha_1)), 2)
fecha_2 = np.array(['2017-08-10', '2015-04-23', '2016-03-10', '2010-11-03'], dtype='datetime64')
lectura_2 = np.around(np.random.rand(len(fecha_2)), 2)

for f1, l1, f2, l2 in zip(fecha_1, lectura_1, fecha_2, lectura_2):
    print(f1, l1, f2, l2)

2017-07-13 0.62 2017-08-10 0.87
2016-01-13 0.12 2015-04-23 0.25
2018-08-13 0.32 2016-03-10 0.48
2020-01-03 0.41 2010-11-03 0.99


In [135]:
# Creación de la condición.
condicion = fecha_1 >= fecha_2
print(condicion)

[False  True  True  True]


### Implementación con `where`

In [136]:
# La funcion where devolverá las lecturas de lectura_1 o lectura_2 según qué fecha sea más reciente.
print(np.where(condicion, lectura_1, lectura_2))

[0.87 0.12 0.32 0.41]


### Implementación con bucles

In [137]:
print(np.array([(l1 if c else l2) for l1, l2, c in zip(lectura_1, lectura_2, condicion)]))

[0.87 0.12 0.32 0.41]


## Ejercicios: La función `where`

### Enunciado

Dados los arrays `examen` y `recuperacion`, que contienen, para cada alumno, su nota en un primer examen y en el examen de recuperación, respectivamente:
1. Obtener las notas finales, asumiento que la nota de recuperación solo se tiene en cuenta si se ha suspendido el primer examen.

In [138]:
np.random.seed(123)
examen = np.around(10 * np.random.rand(10), 1)
recuperacion = np.around(10 * np.random.rand(len(examen)), 1)

print(examen)
print(recuperacion)

[7.  2.9 2.3 5.5 7.2 4.2 9.8 6.8 4.8 3.9]
[3.4 7.3 4.4 0.6 4.  7.4 1.8 1.8 5.3 5.3]


### Respuesta

In [141]:
condicion = examen > 5
print(np.where(condicion,examen,recuperacion))

[7.  7.3 4.4 5.5 7.2 7.4 9.8 6.8 5.3 5.3]


## La función `unique`

In [142]:
# Creación delos datos.
datos = np.random.randint(0, 4, 10)

In [143]:
# Elementos únicos del array.
print(datos)
print(np.unique(datos))

[0 1 0 3 1 3 0 0 0 2]
[0 1 2 3]


## Ejercicios: La función `unique`

### Enunciado

El siguiente array representa los temas elegidos por cada uno de los alumnos para realizar una presentación al final del curso.
1. Saca la lista de temas sin repeticiones.
1. ¿Cuántos temas diferentes se van a tratar en total?

In [144]:
temas = np.array(['Matplotlib', 'Matplotlib', 'Matplotlib', 'Pandas', 'Matplotlib', 'NumPy', 'Sklearn', 'Sklearn', 'Sklearn', 'Pandas', 'NumPy', 'Matplotlib', 'NumPy', 'Matplotlib', 'Pandas'])
print(temas)

['Matplotlib' 'Matplotlib' 'Matplotlib' 'Pandas' 'Matplotlib' 'NumPy'
 'Sklearn' 'Sklearn' 'Sklearn' 'Pandas' 'NumPy' 'Matplotlib' 'NumPy'
 'Matplotlib' 'Pandas']


### Respuesta

In [147]:
print(np.unique(temas))
print(len(np.unique(temas)))

['Matplotlib' 'NumPy' 'Pandas' 'Sklearn']
4


## Arrays booleanos

In [148]:
# Creación de la condición (aleatoria).
condicion = np.random.randn(10) > 0

### Any

In [149]:
print(condicion)
print(condicion.any())

[False False False False False  True False False False False]
True


### All

In [150]:
print(condicion)
print(condicion.all())

[False False False False False  True False False False False]
False


## Ejercicios: Arrays booleanos

### Enunciado

Dado el siguiente array de calificaciones, comprueba:
1. Si ha aprobado algún alumno.
1. Si todos los alumnos han aprobado.
1. Si algún alumno tiene más de 9.

In [151]:
np.random.seed(123)
calificaciones = np.around(10 * np.random.rand(10), 1)
print(calificaciones)

[7.  2.9 2.3 5.5 7.2 4.2 9.8 6.8 4.8 3.9]


### Respuesta

In [154]:
aprobado = calificaciones > 5
sobresaliente = calificaciones > 9 
print(aprobado.any())
print(aprobado.all())
print(aprobado.any())

True
False
True



## Ordenación

In [155]:
# Permutación aleatoria de los números 0-9.
datos = np.random.permutation(10)

### Vectores

In [156]:
print(datos)
datos.sort()
print(datos)

[2 1 8 7 9 4 5 6 3 0]
[0 1 2 3 4 5 6 7 8 9]


In [157]:
# Permutación aleatoria de los números 0-9 (en dos filas).
datos_0 = np.random.permutation(10).reshape(2, 5)
datos_1 = datos_0.copy()

### Matrices por filas

In [158]:
# Ordenación de matrices por filas.
print(datos_0)
datos_0.sort()
print(datos_0)

[[5 1 0 8 6]
 [9 4 2 3 7]]
[[0 1 5 6 8]
 [2 3 4 7 9]]


### Matrices por columnas

In [159]:
# Ordenación de matrices por columnas.
print(datos_1)
datos_1.sort(axis = 0)
print(datos_1)

[[5 1 0 8 6]
 [9 4 2 3 7]]
[[5 1 0 3 6]
 [9 4 2 8 7]]


### Ordenación sobre copia

In [160]:
datos = np.random.permutation(10)
datos_aux = np.copy(datos)

In [161]:
# Ordenación con ndarray.sort.
print(datos)
datos_ord = datos
datos_ord.sort()
print(datos_ord)
print(datos)

[6 8 2 9 5 4 3 1 7 0]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [162]:
datos = np.copy(datos_aux)

In [163]:
# Ordenación con numpy.sort.
print(datos)
datos_ord = np.sort(datos)
print(datos_ord)
print(datos)

[6 8 2 9 5 4 3 1 7 0]
[0 1 2 3 4 5 6 7 8 9]
[6 8 2 9 5 4 3 1 7 0]


### `argsort`

In [164]:
productos = np.array(['leche', 'huevos', 'carne', 'agua'])
cantidades = np.array([3, 4, 10, 1, 5])

In [165]:
# Ordenación usando los índices de argsort.
print("Datos:")
for p, c in zip(productos, cantidades):
    print("%10s\t%2d" % (p, c))

orden = np.argsort(productos)
print("Orden:", orden)

print("Datos ordenados:")
for p, c in zip(productos[orden], cantidades[orden]):
    print("%10s\t%2d" % (p, c))

Datos:
     leche	 3
    huevos	 4
     carne	10
      agua	 1
Orden: [3 2 1 0]
Datos ordenados:
      agua	 1
     carne	10
    huevos	 4
     leche	 3


## Ejercicios: Ordenación

### Enunciado

El siguiente código carga unos ficheros que contienen las notas de un grupo de estudiantes en varias asignaturas. La información está organizada de forma tal que `notas[i]` es la nota del estudiante `estudiantes[i]` en la asignatura `asignaturas[i]`.
1. Crea un array con los nombres de todos los estudiantes y otro con los nombres de todas las asignaturas, sin repeticiones.
1. Para cada estudiante, imprime el número de asignaturas que ha cursado y su nota media. La lista debe estar ordenada según la nota media.
1. Muestra (si los hay) los nombres de todos los estudiantes que hayan cursado todas las asignaturas.
1. Muestra (si los hay) los nombres de todos los estudiantes que hayan aprobado todas las asignaturas que han cursado.
1. Crea un array que contenga, para cada estudiante, su nota en matemáticas en caso de que las haya cursado, y $-1$ en caso contrario.

In [4]:
estudiantes = np.loadtxt("./datos/estudiantes.txt", dtype = str)
asignaturas = np.loadtxt("./datos/asignaturas.txt", dtype = str)
notas = np.loadtxt("./datos/notas.txt")

### Respuesta

In [8]:
nombre_unico = np.unique(estudiantes)
asigna_unico = np.unique(asignaturas)

media = np.array([notas[estudiantes == nombre].mean() for nombre in nombre_unico])
orden = np.argsort(media)

for nombre,nota in zip(nombre_unico[orden[::-1]],media[orden[::-1]]):
    print(nombre,'ha estudiado',len(asignaturas[estudiantes == nombre]),'asignaturas y su media es:',
        '%.2f' % nota)

print('\n')

todas_asig = np.array([len(asignaturas[estudiantes==nombre]) == len(asigna_unico) for nombre in nombre_unico])
print(nombre_unico[todas_asig])

print('\n')

todo_aprob = np.array([(notas[estudiantes==nombre] >= 5).all() for nombre in nombre_unico])
print(nombre_unico[todo_aprob])

Carlos ha estudiado 6 asignaturas y su media es: 7.60
Andrés ha estudiado 5 asignaturas y su media es: 6.76
Alberto ha estudiado 3 asignaturas y su media es: 6.60
Yago ha estudiado 4 asignaturas y su media es: 6.43
Pilar ha estudiado 6 asignaturas y su media es: 5.90
Rosa ha estudiado 5 asignaturas y su media es: 5.84
Juan ha estudiado 3 asignaturas y su media es: 5.53
Ana ha estudiado 6 asignaturas y su media es: 5.35
Manuel ha estudiado 4 asignaturas y su media es: 5.22
Eva ha estudiado 5 asignaturas y su media es: 5.10
Luis ha estudiado 6 asignaturas y su media es: 4.78
Alicia ha estudiado 4 asignaturas y su media es: 4.65
Marta ha estudiado 6 asignaturas y su media es: 4.63
Silvia ha estudiado 5 asignaturas y su media es: 4.48
Daniel ha estudiado 5 asignaturas y su media es: 4.18
Maite ha estudiado 5 asignaturas y su media es: 4.18
Diego ha estudiado 5 asignaturas y su media es: 3.86
Pedro ha estudiado 5 asignaturas y su media es: 3.82
Sonia ha estudiado 6 asignaturas y su media e

# Generación de números aleatorios

## Módulo `random`

### `seed`

In [9]:
# Inicialización de la semilla aleatoria a 123.
np.random.seed(123)

### `rand`

In [10]:
# Generación de 10 números según una uniforme.
print(np.random.rand(10))

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


### `randint`

In [12]:
# Generación de 10 enteros aleatorios entre 0 y 4.
print(np.random.randint(0, 5, 10))

[4 2 4 0 0 1 3 4 4 4]


### `randn`

In [88]:
# Generación de 1000 números aleatorios según una normal (0, 1).
datos = np.random.randn(1000)
print("Media: %.2f" % datos.mean())
print("Std:   %.2f" % datos.std())

Media: 0.02
Std:   1.06


### `permutation`

In [89]:
# Generación de una permutación aleatoria de los números 0-9.
print(np.random.permutation(10))

[4 5 0 1 3 2 7 6 8 9]


In [90]:
# Generación de una permutación aleatoria de los elementos de un array.
datos = np.arange(0, 100, 10)
print(datos)
print(np.random.permutation(datos))

[ 0 10 20 30 40 50 60 70 80 90]
[70 30 90 80 20 40 50  0 10 60]


## Ejercicios: Módulo `random`

### Enunciado

Con la lista de estudiantes del ejercicio anterior, que se carga a continuación:
1. Forma $5$ grupos de $4$ estudiantes cada uno. Los miembros de cada grupo deben ser escogidos al azar.

In [13]:
nombres = np.unique(np.loadtxt('./datos/estudiantes.txt', dtype = str))

### Respuesta

In [25]:
perm = np.random.permutation(np.unique(nombres))
grupoa = perm[:4]
grupob = perm[4:8]
grupoc = perm[8:12]
grupod = perm[12:16]
grupoe = perm[16:20]
print(grupoa,grupob,grupoc,grupod,grupoe)


['Carlos' 'Yago' 'Sonia' 'Pedro'] ['Pilar' 'Manuel' 'Diego' 'Eva'] ['Alicia' 'Rosa' 'Maite' 'Andrés'] ['Juan' 'Alberto' 'Daniel' 'Jesús'] ['Luis' 'Marta' 'Ana' 'Silvia']


# Lectura y escritura de ficheros

## Lectura y escritura de ficheros

### `save` y `load`

In [26]:
# Creación de una matriz y almacenamiento en disco.
datos = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.save("mis_datos", datos)

# Comprobación de que existe el fichero.
!ls -lrt *.npy

"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [27]:
# Borrado de la variable datos y comprobación de que ya no existe.
%xdel datos
%whos ndarray

Variable       Type       Data/Info
-----------------------------------
a              ndarray    4: 4 elems, type `int32`, 16 bytes
asigna_unico   ndarray    6: 6 elems, type `<U12`, 288 bytes
asignaturas    ndarray    100: 100 elems, type `<U12`, 4800 bytes
estudiantes    ndarray    100: 100 elems, type `<U7`, 2800 bytes
grupoa         ndarray    4: 4 elems, type `<U7`, 112 bytes
grupob         ndarray    4: 4 elems, type `<U7`, 112 bytes
grupoc         ndarray    4: 4 elems, type `<U7`, 112 bytes
grupod         ndarray    4: 4 elems, type `<U7`, 112 bytes
grupoe         ndarray    4: 4 elems, type `<U7`, 112 bytes
media          ndarray    20: 20 elems, type `float64`, 160 bytes
nombre_unico   ndarray    20: 20 elems, type `<U7`, 560 bytes
nombres        ndarray    20: 20 elems, type `<U7`, 560 bytes
notas          ndarray    100: 100 elems, type `float64`, 800 bytes
orden          ndarray    20: 20 elems, type `int64`, 160 bytes
perm           ndarray    20: 20 elems, type `<U7`, 5

In [28]:
# Carga del array desde el fichero.
datos = np.load("mis_datos.npy")
print(datos)

[[1 2 3 4]
 [5 6 7 8]]


### `savetxt` y `loadtxt`

In [29]:
# Creación del array de datos aleatorio y almacenamiento en disco como texto separado por comas.
datos = np.random.randn(5,3)
print(datos)
np.savetxt("mis_datos.txt", datos, delimiter = ",", fmt = "%8.4f")
# Contenido del fichero.
!cat mis_datos.txt

[[-1.28966766 -0.08849259 -0.71327372]
 [-1.93927983 -1.02559597  0.64104262]
 [ 0.68867632  0.18890576 -0.0288693 ]
 [-0.83104099 -0.49990905  0.2372282 ]
 [-0.19119611  1.05496154 -2.47815242]]


"cat" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [30]:
# Carga del contenido del fichero en la variable new_datos.
new_datos = np.loadtxt("mis_datos.txt", delimiter = ",")
print(new_datos)

[[-1.2897 -0.0885 -0.7133]
 [-1.9393 -1.0256  0.641 ]
 [ 0.6887  0.1889 -0.0289]
 [-0.831  -0.4999  0.2372]
 [-0.1912  1.055  -2.4782]]


## Ejercicios: Lectura y escritura de ficheros

### Enunciado

Crea un vector de $10000$ números aleatorios, siguiendo una Gaussiana estándar. A continuación:
1. Almacena el vector en formato binario.
1. Almacena el vector en formato texto, separando los campos con `;`.
1. Compara el tamaño de ambos ficheros.

### Respuesta

In [32]:
vector = np.random.randn(1000)
np.save('mi_normal',vector)
np.savetxt('mi_normal2.txt',vector,delimiter=';',fmt='%8.4f')

# *Broadcasting*

## *Broadcasting*

### Escalar

In [2]:
# Operación de un array con un escalar.
a = np.array([1, 2, 3])
b = 1

print(a)
print("+")
print(b)
print("-------")
print(a + b)

[1 2 3]
+
1
-------
[2 3 4]


### Vector

In [3]:
# Operación entre dos arrays, fila y columna.
a = np.array([[1, 2, 3]])
b = np.array([[1], [2]])
print(a)
print("x")
print(b)
print("---------")
print(a * b)

[[1 2 3]]
x
[[1]
 [2]]
---------
[[1 2 3]
 [2 4 6]]


### Matriz

In [4]:
# Para sumar dos arrays, uno (5x2) y otro (5x3) para obtener un array 5x2x3, primero se transforman en 5x2x1 y en 5x1x3, usandonp.newaxis.
a = np.random.randint(10, size = (5, 2))
b = np.random.randint(10, size = (5, 3))

a = a[:,:,np.newaxis]
b = b[:,np.newaxis,:]

print(a[:, :, 0])
print("+")
print(b[:, 0, :])
print("--------------")
print(a + b)

[[5 6]
 [5 8]
 [7 6]
 [4 6]
 [7 1]]
+
[[4 7 6]
 [4 5 7]
 [5 2 3]
 [6 4 1]
 [7 6 4]]
--------------
[[[ 9 12 11]
  [10 13 12]]

 [[ 9 10 12]
  [12 13 15]]

 [[12  9 10]
  [11  8  9]]

 [[10  8  5]
  [12 10  7]]

 [[14 13 11]
  [ 8  7  5]]]


## Ejercicios: *Broadcasting*

### Enunciado

El siguiente código carga unos ficheros que contienen las notas de un grupo de estudiantes en varias asignaturas. La información está organizada de forma tal que `notas[i]` es la nota del estudiante `estudiantes[i]` en la asignatura `asignaturas[i]`.
1. Repite el ejericicio de imprimir, para cada estudiante, el número de asignaturas que ha cursado y su nota media. Esta vez, no utilices bucles salvo para imprimir los resultados.
1. Compara el tiempo de ejecución con el método con bucles usado antes.

In [ ]:
estudiantes = np.loadtxt("./datos/estudiantes.txt", dtype = str)
asignaturas = np.loadtxt("./datos/asignaturas.txt", dtype = str)
notas = np.loadtxt("./datos/notas.txt")

### Respuesta